ADMIN_ROLE = "admin"
RECEPTIONIST_ROLE = "receptionist"
HEALTHCARE_PROFESSIONAL_ROLE = "healthcare_professional"
INTEGRATION_ROLE = "integration"

ALL_ROLES = [ADMIN_ROLE, RECEPTIONIST_ROLE, HEALTHCARE_PROFESSIONAL_ROLE, INTEGRATION_ROLE]