name: Security Gate

on: push

jobs:
  scan_de_seguranca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkou
        uses: actions/checkout@v4

      - name: Instalar o Bandit (Scanner SAST para Python)
        run: pip install bandit

      - name: SAST - Analisar o codigo fonte (Bloqueia falhas HIGH ou +)
        run: bandit -r . -lll

      - name: SCA - Scanner de vulnerabilidades (Bloqueia HIGH-CRITICAS)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'